apiVersion: v1
kind: Service
metadata:
        name: test-api-service
spec:
        type: NodePort
        selector:
                component: test-api
        ports:
                - port: 3000
                  targetPort: 3000
                  nodePort: 31515
